<?php require "header.phtml";?> <!-- Incluye la cabecera de la página -->

<div class="container"> <!-- Inicia un contenedor -->
    <h1 class="text-center text-white rounded bg-primary">EDICION DE PLAN</h1> <!-- Título de la página -->
    <div class="d-flex justify-content-center"> <!-- Contenedor con contenido centrado en horizontal -->
        <form class="col-6 text-center" action="editPlan" method="POST"> <!-- Formulario para editar un plan -->
            <div class="form-floating mb-3 text-center"> <!-- Grupo de elementos de formulario -->
                <div class="form-floating m-3">
                    <input type="number" class="form-control" name="IDPlan" value="<?= $datosUsuario->ID ?>" readonly>
                    <label for="floatingInput">ID Plan</label>
                </div>
                <div class="form-floating m-3">
                    <input type="text" class="form-control" id="floatingInput" name="Plan" value="<?= $datosUsuario->Plan ?>">
                    <label for="floatingInput">Plan</label>
                </div>
                <div class="form-floating m-3">
                    <input type="number" class="form-control" name="Duracion" value="<?= $datosUsuario->Duracion ?>">
                    <label for="floatingPassword">Duración</label>
                </div>
                <div class="form-floating m-3">
                    <input type="number" class="form-control" name="Precio" value="<?= $datosUsuario->Precio ?>">
                    <label for="floatingPassword">Precio</label>
                </div>
                <div class="form-floating m-3">
                    <input type="number" class="form-control" name="Porcentaje" value="<?= $datosUsuario->Porcentaje ?>">
                    <label for="floatingPassword">Porcentaje</label>
                </div>
                <button type="submit" class="btn btn-primary">Editar Plan</button> <!-- Botón para enviar el formulario -->
            </div>
        </form>
    </div>
</div>

<?php require_once "footer.phtml";?> <!-- Incluye el pie de página -->